---
title: "BE : une introduction à l'analyse en composantes indépendantes (ICA)."
---

## Présentation du problème

Dans ce bureau d'étude nous allons étudier le difficile problème de la séparation « aveugle » des sources que nous allons expliquer dans la suite. Lorsque l'on observe un jeu de données (par exemple issues de capteurs comme des antennes, microphones ou des images, etc...), ces données observées peuvent être issu d'un mélange de signaux sources. Le problème est alors d'arriver à isoler les signaux sources à partir des données observées mélangées. L'exemple paradigmatique est celui du « party cocktail problem », où l'on place plusieurs microphones dans une salle, ces microphones enregistrent des mélanges de conversation et le but de la séparation « aveugle » des sources est d'isoler les différentes voix (= les sources). Ce type de problème, dans sa formulation la plus générale, n'a en général aucune solution théorique mais il est néanmoins possible en ajoutant des hypothèses de trouver des « solutions acceptables ». Nous allons voir une catégorie d'approche qui en imposant certaines conditions permet d'avoir des résultats (très) corrects : l'analyse en composantes indépendantes (independent component analysis que nous abrégerons par ICA). 


## Sujet complet

Le développement complet des hypothèses, le formalisme et les questions intermédiaires sont disponibles dans le document ci-dessous :

[📄 Télécharger / Consulter le sujet au format PDF](sujets_BE/Ma315_BE_2023.pdf)

## Prérequis 

Probabilités et statistiques de base, bases du calcul différentiel. 