---
title: "BE : Introduction à la géométrie de l'information ou comment calculer pour comprendre pourquoi on se trompe."
---

## Présentation du problème

Le projet proposé suit deux buts principaux : donner une introduction à la géométrie de l'information, on obtient un point de vue différent sur les probabilités et les statistiques (en espérant que cet autre point de vue réconcilie un peu les plus récalcitrants aux statistiques...) et proposer une sorte de « laboratoire » d'épistémologie quantitative. Dans ce bureau d'étude nous allons réfléchir aux biais de cognitions et plus généralement voir par le calcul pourquoi on est souvent conduit à des erreurs de raisonnement. Nous prendrons la géométrie de l'information comme une sorte de modèle normatif de la rationalité face à de l'information à traiter et nous verrons en quoi cela peut nous éclairer et nuancer nos raisonnements. La longueur (en page) du sujet s'explique pour plusieurs raisons : 

• la présence de nombreux encart « Pause épistémologique », détaillant des biais cognitifs ou des remarques liés aux formalismes introduit. Certains de ces biais ou remarques pourraient s'appliquer à plusieurs questions du sujet, pour ne pas alourdir nous ne les répéterons pas (à vous d'identifier les différentes expressions formelles d'un même biais).

• les questions sont souvent très découpées et les réponses sont souvent rapides. 

• les questions de statistiques et de probabilités demandent souvent un long « contexte » pour être formulées correctement.



La spécificité de ce sujet est de traiter de biais cognitif de manière formelle et quantitative. En mobilisant vos connaissances diverses, une consigne générale sera de produire des exemples sourcés des différents biais et de regarder les réponses apportées par la formalisation du sujet. 



Attention les sujets et thèmes abordés ne le sont qu'en surface et il y aurait beaucoup (trop) de choses à dire sur de nombreux points. Vos ouvertures personnelles (en lien avec le sujet bien sûr!) et réflexions seront fortement valorisées. 


## Sujet complet

Le développement complet des hypothèses, le formalisme et les questions intermédiaires sont disponibles dans le document ci-dessous :

[📄 Télécharger / Consulter le sujet au format PDF](sujets_BE/Ma315_BE_2025_26.pdf)

## Prérequis 

Probabilités et statistiques de base, bases du calcul différentiel. 